
#
option(USE_OPENCV_WRAPPER_SHARED_LIBS "${project_name} use opencv_wrapper by shared library." ON)
option(USE_OPENCV_WRAPPER_STATIC_LIBS "${project_name} use opencv_wrapper by static library." OFF)
option(USE_OPENCV_WRAPPER_OBJECT_LIBS "${project_name} use opencv_wrapper by object library." OFF)

if (USE_OPENCV_WRAPPER_SHARED_LIBS)
  message(STATUS "======>> ${project_name} use opencv_wrapper by shared library.")
  set(common_name opencv_wrapper_lib)
  if(IOS OR MACOS OR ANDROID)
    set(common_name opencv_wrapper_common_lib)  
  endif()
elseif(USE_OPENCV_WRAPPER_STATIC_LIBS)
  message(STATUS "======>> ${project_name} use opencv_wrapper by static library.")
  set(common_name opencv_wrapper_static)
  if(IOS OR MACOS OR ANDROID)
    set(common_name opencv_wrapper_common_static)  
  endif()
elseif(USE_OPENCV_WRAPPER_OBJECT_LIBS)
  message(STATUS "======>> ${project_name} use opencv_wrapper by object library.")
  set(common_name opencv_wrapper_object)
  if(IOS OR MACOS OR ANDROID)
    set(common_name opencv_wrapper_common_object)  
  endif()
endif()
